title = "Sea chirps"
baseURL = "https://nedlrichards.github.io/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Webpage of Edward L Richards"
  facebook = ""
  twitter = "https://twitter.com/seachirps"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  name = "Edward L. Richards"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  #featured_image = "/images/beach_jkd.jpg"
  cloudinary_base_url ="https://res.cloudinary.com/dqg4qqb1z"
  featured_image = "https://res.cloudinary.com/dqg4qqb1z/w_auto,c_scale,f_auto,q_auto,dpr_auto/beach_jkd.jpg"
  recent_posts_number = 2
